# Generated by Django 2.2.7 on 2019-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        default="media/work.jpg",
                        upload_to="media",
                        verbose_name="Miniaturka na stronie glownej",
                    ),
                ),
                (
                    "categories",
                    models.CharField(max_length=70, verbose_name="Kategoria"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/work.jpg",
                        upload_to="media",
                        verbose_name="Tlo menu",
                    ),
                ),
                ("dish", models.TextField(max_length=150, verbose_name="Nazwa dania")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Lista skladnikow"),
                ),
                ("price", models.IntegerField()),
                ("size", models.IntegerField()),
            ],
        ),
    ]
