# Generated by Django 2.2.7 on 2019-12-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denmark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/work.jpg",
                        upload_to="media",
                        verbose_name="Tlo menu",
                    ),
                ),
                ("dish", models.TextField(max_length=150, verbose_name="Nazwa dania")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Lista skladnikow"),
                ),
                ("price", models.IntegerField()),
                ("size", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(model_name="restaurant", name="description",),
        migrations.RemoveField(model_name="restaurant", name="dish",),
        migrations.RemoveField(model_name="restaurant", name="image",),
        migrations.RemoveField(model_name="restaurant", name="price",),
        migrations.RemoveField(model_name="restaurant", name="size",),
    ]
