# Generated by Django 2.2.7 on 2019-12-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_auto_20191207_2109"),
    ]

    operations = [
        migrations.RemoveField(model_name="denmark", name="image",),
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                default="media/work.jpg", upload_to="media", verbose_name="Tlo menu"
            ),
        ),
    ]
