# Generated by Django 2.2.8 on 2019-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_auto_20191207_2135"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        default="media/work.jpg",
                        upload_to="media",
                        verbose_name="Miniaturka na stronie glownej",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/work.jpg",
                        upload_to="media",
                        verbose_name="Tlo menu",
                    ),
                ),
                ("name", models.CharField(max_length=70, verbose_name="Nazwa")),
            ],
        ),
        migrations.RenameModel(old_name="Denmark", new_name="Menu",),
        migrations.DeleteModel(name="Restaurant",),
    ]
