# Generated by Django 2.2.8 on 2019-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20191209_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
